# Generated by Django 3.1.7 on 2022-03-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=280)),
                ('cost', models.IntegerField()),
                ('image', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
